"""LaTeX / PDF export for the comparison view.

Produces a zip containing:
  - table.tex   booktabs-style summary table (via pandas.to_latex)
  - curves.pdf  4-panel training curves (val PSNR, val SSIM, train loss, val loss)

Designed to be \\input'd directly into a LaTeX document.
"""
from __future__ import annotations

import io
import zipfile
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse

from backend.services import run_scanner

router = APIRouter()


_PALETTE = [
    "#1f77b4", "#d62728", "#2ca02c", "#9467bd",
    "#ff7f0e", "#17becf", "#8c564b", "#e377c2",
]


def _tex_escape(value: str) -> str:
    return (
        value.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("~", r"\textasciitilde{}")
        .replace("^", r"\textasciicircum{}")
    )


def _fmt(value, spec: str, na: str = "---") -> str:
    if value is None:
        return na
    return format(value, spec)


def _build_table_tex(details) -> str:
    columns = [
        "Model",
        "Arch",
        "Scale",
        "Epochs",
        "Best PSNR (dB)",
        "Best SSIM",
        "Final val loss",
    ]
    column_format = "l l c r r r r"

    body_rows = []
    for d in details:
        body_rows.append(" & ".join([
            _tex_escape(d.model_name),
            _tex_escape(d.arch),
            f"$\\times${d.scale}",
            str(d.completed_epochs),
            _fmt(d.best_psnr, ".3f"),
            _fmt(d.best_ssim, ".4f"),
            _fmt(d.final_val_loss, ".5f"),
        ]) + r" \\")

    lines = [
        "% Generated by SISR Thesis Manager - "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "% Requires \\usepackage{booktabs} in your preamble.",
        f"\\begin{{tabular}}{{{column_format}}}",
        "\\toprule",
        " & ".join(columns) + r" \\",
        "\\midrule",
        *body_rows,
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def _build_curves_pdf(details) -> bytes:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(2, 2, figsize=(10, 7.5))
    panels = [
        (axes[0, 0], "val_psnr", "Val PSNR (dB)"),
        (axes[0, 1], "val_ssim", "Val SSIM"),
        (axes[1, 0], "train_loss", "Train loss"),
        (axes[1, 1], "val_loss", "Val loss"),
    ]

    for ax, field, ylabel in panels:
        for idx, d in enumerate(details):
            epochs = [m.epoch for m in d.metrics]
            values = [getattr(m, field) for m in d.metrics]
            if not epochs:
                continue
            ax.plot(
                epochs, values,
                label=f"{d.model_name} ({d.arch} x{d.scale})",
                color=_PALETTE[idx % len(_PALETTE)],
                linewidth=1.4,
            )
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.grid(True, alpha=0.3)
        if field.endswith("loss"):
            ax.set_yscale("log")

    handles, labels = axes[0, 0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="lower center", ncol=min(len(details), 3), fontsize=9)
        fig.subplots_adjust(bottom=0.12 + 0.03 * ((len(details) - 1) // 3))

    fig.suptitle("Training curves — comparison", fontsize=12)
    fig.tight_layout(rect=(0, 0.08, 1, 0.96))

    buf = io.BytesIO()
    fig.savefig(buf, format="pdf", bbox_inches="tight")
    plt.close(fig)
    return buf.getvalue()


def _safe_slug() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


@router.get("/export/latex")
def export_latex(runs: list[str] = Query(default=[])):
    if not runs:
        raise HTTPException(status_code=400, detail="Pass at least one ?runs=<run_id>.")

    details = []
    for run_id in runs:
        d = run_scanner.get_run_detail(run_id)
        if d is None:
            raise HTTPException(status_code=404, detail=f"Run not found: {run_id}")
        details.append(d)

    table_tex = _build_table_tex(details)
    curves_pdf = _build_curves_pdf(details)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("table.tex", table_tex)
        zf.writestr("curves.pdf", curves_pdf)

    buf.seek(0)
    filename = f"sisr_export_{_safe_slug()}.zip"
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
