model_name: "VideoESPCN_Vimeo90K_x2_3f"
arch: "VideoESPCN"
dataset_name: "Vimeo90K"
run_group: "vsr"
dataset_type: "vimeo90k_raw"
vimeo90k_raw_root: "data/raw/vimeo90k_kaggle"
scale: 2
num_frames: 3
hidden_channels: 32
patch_size: 0
batch_size: 16
epochs: 100
lr: 0.001
num_workers: 4
device: "auto"
amp: true
grayscale: true
augment: false
samples_per_epoch: 16000
val_samples: 948
