model_name: "Pilot_VSRBasic_Vimeo90K_x2_3f"
arch: "VSRBasic"
dataset_name: "Vimeo90K"
run_group: "vsr"
dataset_type: "vimeo90k_raw"
vimeo90k_raw_root: "data/raw/vimeo90k_kaggle"
scale: 2
num_frames: 3
hidden_channels: 48
num_blocks: 4
patch_size: 0
batch_size: 4
epochs: 5
lr: 0.0002
num_workers: 4
device: "auto"
amp: true
grayscale: true
augment: false
samples_per_epoch: 2000
val_samples_per_epoch: 200
early_stopping_patience: 8
save_best_only: true
seed: 42
